server:
  port: 7088
spring:
  application:
    admin:
      enabled: true
    name: blog
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/1024notes
    username: postgres
    password: 123456
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 3d9da33b99dcdfb03693
            client-secret: 62cf2152039998454204c776ba94c66b2abc732c
  jackson:
    date-format: yyyy.MM.dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
logging:
  level:
    org.springframework.r2dbc: DEBUG

jwt:
  expiration:
    duration: 3600